-- Populates Customer Table
INSERT INTO Customers (fname, lname, email) VALUES ('JENNI','KAPADIA','JENNI@KAPADIA.com');
INSERT INTO Customers (fname, lname, email) VALUES ('JANISE','PATRAM','JANISE@PATRAM.com');
INSERT INTO Customers (fname, lname, email) VALUES ('JANETT','BELLEMORE','JANETT@BELLEMORE.com');
INSERT INTO Customers (fname, lname, email) VALUES ('RIGOBERTO','KOLODZIK','RIGOBERTO@KOLODZIK.com');
INSERT INTO Customers (fname, lname, email) VALUES ('EXIE','SKETO','EXIE@SKETO.com');
INSERT INTO Customers (fname, lname, email) VALUES ('LORENZO','FREHSE','LORENZO@FREHSE.com');
INSERT INTO Customers (fname, lname, email) VALUES ('SIMONNE','PEEDE','SIMONNE@PEEDE.com');
INSERT INTO Customers (fname, lname, email) VALUES ('CHAN','LIGHTER','CHAN@LIGHTER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('CARMAN','KOHANEK','CARMAN@KOHANEK.com');
INSERT INTO Customers (fname, lname, email) VALUES ('CARMELLA','ALSUP','CARMELLA@ALSUP.com');
INSERT INTO Customers (fname, lname, email) VALUES ('CHANG','DELAHOZ','CHANG@DELAHOZ.com');
INSERT INTO Customers (fname, lname, email) VALUES ('DEADRA','VALENZIA','DEADRA@VALENZIA.com');
INSERT INTO Customers (fname, lname, email) VALUES ('LURLINE','SCORZELLI','LURLINE@SCORZELLI.com');
INSERT INTO Customers (fname, lname, email) VALUES ('CHASIDY','DIEKEMPER','CHASIDY@DIEKEMPER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('NANA','CHARNETSKI','NANA@CHARNETSKI.com');
INSERT INTO Customers (fname, lname, email) VALUES ('SHANICE','ILK','SHANICE@ILK.com');
INSERT INTO Customers (fname, lname, email) VALUES ('BELIA','VANDERBILT','BELIA@VANDERBILT.com');
INSERT INTO Customers (fname, lname, email) VALUES ('SUZANN','MENKHAUS','SUZANN@MENKHAUS.com');
INSERT INTO Customers (fname, lname, email) VALUES ('TA','FAAMAUSILI','TA@FAAMAUSILI.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ELANE','GAOIRAN','ELANE@GAOIRAN.com');
INSERT INTO Customers (fname, lname, email) VALUES ('LEIDA','VIRGADAMO','LEIDA@VIRGADAMO.com');
INSERT INTO Customers (fname, lname, email) VALUES ('MELINDA','SPRUNGER','MELINDA@SPRUNGER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('LIZABETH','HALLANGER','LIZABETH@HALLANGER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('CHARMAIN','WASTLER','CHARMAIN@WASTLER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('VANETTA','SOTELO','VANETTA@SOTELO.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ADELINE','SPEESE','ADELINE@SPEESE.com');
INSERT INTO Customers (fname, lname, email) VALUES ('MOSE','MUSTON','MOSE@MUSTON.com');
INSERT INTO Customers (fname, lname, email) VALUES ('IDALIA','WANCZYK','IDALIA@WANCZYK.com');
INSERT INTO Customers (fname, lname, email) VALUES ('KHALILAH','SIEPERT','KHALILAH@SIEPERT.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ANTOINETTE','BOUN','ANTOINETTE@BOUN.com');
INSERT INTO Customers (fname, lname, email) VALUES ('HILARY','KIDA','HILARY@KIDA.com');
INSERT INTO Customers (fname, lname, email) VALUES ('EMELDA','DOUVIER','EMELDA@DOUVIER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('AYANA','FLECHTNER','AYANA@FLECHTNER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('MINERVA','FRIDEL','MINERVA@FRIDEL.com');
INSERT INTO Customers (fname, lname, email) VALUES ('KARI','REBOLD','KARI@REBOLD.com');
INSERT INTO Customers (fname, lname, email) VALUES ('DARA','BALSIGER','DARA@BALSIGER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('SHANNAN','ACOCK','SHANNAN@ACOCK.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ADINA','STEINDORF','ADINA@STEINDORF.com');
INSERT INTO Customers (fname, lname, email) VALUES ('KENDRICK','HEMMIS','KENDRICK@HEMMIS.com');
INSERT INTO Customers (fname, lname, email) VALUES ('LATOYA','HIMMELBERG','LATOYA@HIMMELBERG.com');
INSERT INTO Customers (fname, lname, email) VALUES ('JULIET','CONFORTE','JULIET@CONFORTE.com');
INSERT INTO Customers (fname, lname, email) VALUES ('EUGENA','NIZOLEK','EUGENA@NIZOLEK.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ROBERT','TRELEASE','ROBERT@TRELEASE.com');
INSERT INTO Customers (fname, lname, email) VALUES ('VIOLETTE','BANAGAN','VIOLETTE@BANAGAN.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ALLEN','PASION','ALLEN@PASION.com');
INSERT INTO Customers (fname, lname, email) VALUES ('ROSELLE','HEMMIS','ROSELLE@HEMMIS.com');
INSERT INTO Customers (fname, lname, email) VALUES ('RUBY','UPEGUI','RUBY@UPEGUI.com');
INSERT INTO Customers (fname, lname, email) VALUES ('LAVERNA','FRASIER','LAVERNA@FRASIER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('HELGA','BLIEMEISTER','HELGA@BLIEMEISTER.com');
INSERT INTO Customers (fname, lname, email) VALUES ('BRUCE','BOXLEITNER','BRUCE@BOXLEITNER.com');

--Populates Publisher Table
INSERT INTO Publishers (name) VALUES ('Baker Book House');
INSERT INTO Publishers (name) VALUES ('Pantheon Books at Random House');
INSERT INTO Publishers (name) VALUES ('Wesleyan University Press');
INSERT INTO Publishers (name) VALUES ('Hutchinson');
INSERT INTO Publishers (name) VALUES ('Legend Books ');
INSERT INTO Publishers (name) VALUES ('Gregg Press ');
INSERT INTO Publishers (name) VALUES ('Central European University Press');
INSERT INTO Publishers (name) VALUES ('Bantam Books ');
INSERT INTO Publishers (name) VALUES ('Greenleaf Book Group');
INSERT INTO Publishers (name) VALUES ('Akashic Books ');
INSERT INTO Publishers (name) VALUES ('Harlequin Enterprises Ltd');
INSERT INTO Publishers (name) VALUES ('Newnes');
INSERT INTO Publishers (name) VALUES ('MIT Press');
INSERT INTO Publishers (name) VALUES ('Pavilion Books ');
INSERT INTO Publishers (name) VALUES ('McFarland & Company');
INSERT INTO Publishers (name) VALUES ('Boydell & Brewer');
INSERT INTO Publishers (name) VALUES ('Sussex Academic Press');
INSERT INTO Publishers (name) VALUES ('Wipf and Stock');
INSERT INTO Publishers (name) VALUES ('Ticonderoga Publications');
INSERT INTO Publishers (name) VALUES ('Holland Park Press');
INSERT INTO Publishers (name) VALUES ('Bobbs-Merrill Company ');
INSERT INTO Publishers (name) VALUES ('Carnegie Mellon University Press');
INSERT INTO Publishers (name) VALUES ('Academic Press ');
INSERT INTO Publishers (name) VALUES ('Gefen Publishing House');
INSERT INTO Publishers (name) VALUES ('Walter de Gruyter');
INSERT INTO Publishers (name) VALUES ('Mandrake Press');
INSERT INTO Publishers (name) VALUES ('New Holland Publishers');
INSERT INTO Publishers (name) VALUES ('Blackie and Son Limited');
INSERT INTO Publishers (name) VALUES ('Collector''s Guide Publishing');
INSERT INTO Publishers (name) VALUES ('Universal Publishers (United States)');
INSERT INTO Publishers (name) VALUES ('Mother Tongue Publishing');
INSERT INTO Publishers (name) VALUES ('Philosophy Documentation Center');
INSERT INTO Publishers (name) VALUES ('Scribner (UK)');
INSERT INTO Publishers (name) VALUES ('Gaspereau Press');
INSERT INTO Publishers (name) VALUES ('Manchester University Press');
INSERT INTO Publishers (name) VALUES ('Information Age Publishing');
INSERT INTO Publishers (name) VALUES ('WSOY, Finland');
INSERT INTO Publishers (name) VALUES ('Candlewick Press');
INSERT INTO Publishers (name) VALUES ('Summit Media');
INSERT INTO Publishers (name) VALUES ('Everyman''s Library');
INSERT INTO Publishers (name) VALUES ('John Lane');
INSERT INTO Publishers (name) VALUES ('Serif');
INSERT INTO Publishers (name) VALUES ('Thieme Medical Publishers');
INSERT INTO Publishers (name) VALUES ('W. H. Allen Ltd ');
INSERT INTO Publishers (name) VALUES ('Leaf Books');
INSERT INTO Publishers (name) VALUES ('Robert Hale Publishing ');
INSERT INTO Publishers (name) VALUES ('Carlton Books UK');
INSERT INTO Publishers (name) VALUES ('D. Reidel ');
INSERT INTO Publishers (name) VALUES ('CRC Press');
INSERT INTO Publishers (name) VALUES ('Parachute Publishing');
INSERT INTO Publishers (name) VALUES ('Cisco Press');
INSERT INTO Publishers (name) VALUES ('Troubador Press ');
INSERT INTO Publishers (name) VALUES ('FabJob');
INSERT INTO Publishers (name) VALUES ('Osprey Publishing');
INSERT INTO Publishers (name) VALUES ('Orion Books');
INSERT INTO Publishers (name) VALUES ('Kensington Books');
INSERT INTO Publishers (name) VALUES ('Greenleaf Publishing Ltd');
INSERT INTO Publishers (name) VALUES ('Chick Publications');
INSERT INTO Publishers (name) VALUES ('Thames & Hudson (UK)');
INSERT INTO Publishers (name) VALUES ('Grosset & Dunlap ');
INSERT INTO Publishers (name) VALUES ('Copper Canyon Press');
INSERT INTO Publishers (name) VALUES ('Virago Press');
INSERT INTO Publishers (name) VALUES ('University Press of Kentucky');
INSERT INTO Publishers (name) VALUES ('Black Library');
INSERT INTO Publishers (name) VALUES ('Abilene Christian University Press');
INSERT INTO Publishers (name) VALUES ('Harry N. Abrams, Inc.');
INSERT INTO Publishers (name) VALUES ('Etruscan Press');
INSERT INTO Publishers (name) VALUES ('BBC Books');
INSERT INTO Publishers (name) VALUES ('Other Press');
INSERT INTO Publishers (name) VALUES ('Oberon Books');
INSERT INTO Publishers (name) VALUES ('University of California Press');
INSERT INTO Publishers (name) VALUES ('Dalkey Archive Press ');
INSERT INTO Publishers (name) VALUES ('Myriad Editions');
INSERT INTO Publishers (name) VALUES ('Kumarian Press ');
INSERT INTO Publishers (name) VALUES ('City Lights Publishers');
INSERT INTO Publishers (name) VALUES ('Basic Books');
INSERT INTO Publishers (name) VALUES ('Fulcrum Press');
INSERT INTO Publishers (name) VALUES ('Packt Publishing');
INSERT INTO Publishers (name) VALUES ('HarperCollins Publishers');
INSERT INTO Publishers (name) VALUES ('NRC Research Press');
INSERT INTO Publishers (name) VALUES ('Mirage Publishing (UK) ');
INSERT INTO Publishers (name) VALUES ('Longman');
INSERT INTO Publishers (name) VALUES ('Liverpool University Press');
INSERT INTO Publishers (name) VALUES ('Pluto Press');
INSERT INTO Publishers (name) VALUES ('Hogarth Press');
INSERT INTO Publishers (name) VALUES ('Applewood Books');
INSERT INTO Publishers (name) VALUES ('Berg Publishers ');
INSERT INTO Publishers (name) VALUES ('Chambers Harrap');
INSERT INTO Publishers (name) VALUES ('No Starch Press');
INSERT INTO Publishers (name) VALUES ('Greenery Press');
INSERT INTO Publishers (name) VALUES ('Sinclair-Stevenson Ltd');
INSERT INTO Publishers (name) VALUES ('Sounds True');
INSERT INTO Publishers (name) VALUES ('Koren Publishers Jerusalem ');
INSERT INTO Publishers (name) VALUES ('Papadakis Publisher');
INSERT INTO Publishers (name) VALUES ('Apress ');
INSERT INTO Publishers (name) VALUES ('University of South Carolina Press');
INSERT INTO Publishers (name) VALUES ('Continuum International Publishing Group ');
INSERT INTO Publishers (name) VALUES ('KTAV Publishing House');
INSERT INTO Publishers (name) VALUES ('Springer Science+Business Media (formally Springer Verlag)');
INSERT INTO Publishers (name) VALUES ('Yale University Press');
INSERT INTO Publishers (name) VALUES ('Ballantine Books');
INSERT INTO Publishers (name) VALUES ('Medknow Publications');
INSERT INTO Publishers (name) VALUES ('Horizon Scientific Press (UK)');
INSERT INTO Publishers (name) VALUES ('Tor Books');
INSERT INTO Publishers (name) VALUES ('Michael O''Mara Books');
INSERT INTO Publishers (name) VALUES ('Atheneum Publishers ');
INSERT INTO Publishers (name) VALUES ('ArtScroll ');
INSERT INTO Publishers (name) VALUES ('Polity');
INSERT INTO Publishers (name) VALUES ('Parragon');
INSERT INTO Publishers (name) VALUES ('Orchard Books');
INSERT INTO Publishers (name) VALUES ('Bloomsbury Publishing Plc ');
INSERT INTO Publishers (name) VALUES ('Dick and Fitzgerald');
INSERT INTO Publishers (name) VALUES ('William Edwin Rudge');
INSERT INTO Publishers (name) VALUES ('Martinus Nijhoff Publishers ');
INSERT INTO Publishers (name) VALUES ('Prentice Hall');
INSERT INTO Publishers (name) VALUES ('O''Reilly Media');
INSERT INTO Publishers (name) VALUES ('Twelveheads Press');
INSERT INTO Publishers (name) VALUES ('Crown Publishing Group ');
INSERT INTO Publishers (name) VALUES ('Woodhead Publishing');
INSERT INTO Publishers (name) VALUES ('A. C. McClurg');
INSERT INTO Publishers (name) VALUES ('HMSO');
INSERT INTO Publishers (name) VALUES ('Crocker & Brewster');
INSERT INTO Publishers (name) VALUES ('University of Akron Press');
INSERT INTO Publishers (name) VALUES ('Bowes & Bowes');
INSERT INTO Publishers (name) VALUES ('NYRB Classics');
INSERT INTO Publishers (name) VALUES ('Emerald Group Publishing');
INSERT INTO Publishers (name) VALUES ('SPCK');
INSERT INTO Publishers (name) VALUES ('Phaidon Press');
INSERT INTO Publishers (name) VALUES ('Marshall Cavendish');
INSERT INTO Publishers (name) VALUES ('Tupelo Press');
INSERT INTO Publishers (name) VALUES ('John Wiley & Sons (Wiley)');
INSERT INTO Publishers (name) VALUES ('Virgin Publishing');
INSERT INTO Publishers (name) VALUES ('Prometheus Books');
INSERT INTO Publishers (name) VALUES ('Que Publishing');
INSERT INTO Publishers (name) VALUES ('Target Books ');
INSERT INTO Publishers (name) VALUES ('The Good Book Company (UK)');
INSERT INTO Publishers (name) VALUES ('Dedalus Books');
INSERT INTO Publishers (name) VALUES ('Collins');
INSERT INTO Publishers (name) VALUES ('Tartarus Press');
INSERT INTO Publishers (name) VALUES ('John Murray');
INSERT INTO Publishers (name) VALUES ('Ignatius Press');
INSERT INTO Publishers (name) VALUES ('Third World Press');
INSERT INTO Publishers (name) VALUES ('Baen Books');
INSERT INTO Publishers (name) VALUES ('Mapin Publishing');
INSERT INTO Publishers (name) VALUES ('Island Press');
INSERT INTO Publishers (name) VALUES ('Viking Press ');
INSERT INTO Publishers (name) VALUES ('Poisoned Pen Press');
INSERT INTO Publishers (name) VALUES ('InterVarsity Press ');
INSERT INTO Publishers (name) VALUES ('Good News Publishers');
INSERT INTO Publishers (name) VALUES ('ATOM Books ');
INSERT INTO Publishers (name) VALUES ('Two Dollar Radio');
INSERT INTO Publishers (name) VALUES ('Wrecking Ball Press');
INSERT INTO Publishers (name) VALUES ('Open University Press');
INSERT INTO Publishers (name) VALUES ('Free Press');
INSERT INTO Publishers (name) VALUES ('B & W Publishing');
INSERT INTO Publishers (name) VALUES ('Rowman & Littlefield');
INSERT INTO Publishers (name) VALUES ('Secker & Warburg');
INSERT INTO Publishers (name) VALUES ('Paulist Press');
INSERT INTO Publishers (name) VALUES ('George H. Doran Company');
INSERT INTO Publishers (name) VALUES ('Policy Press');
INSERT INTO Publishers (name) VALUES ('Kluwer Academic Publishers');
INSERT INTO Publishers (name) VALUES ('Top Shelf Productions');
INSERT INTO Publishers (name) VALUES ('Frederick Fell Publishers, Inc.');
INSERT INTO Publishers (name) VALUES ('Arcadia Publishing ');
INSERT INTO Publishers (name) VALUES ('Carlton Publishing Group UK');
INSERT INTO Publishers (name) VALUES ('Sams Publishing');
INSERT INTO Publishers (name) VALUES ('Puffin Books ');
INSERT INTO Publishers (name) VALUES ('Holt McDougal');
INSERT INTO Publishers (name) VALUES ('Bloodaxe Books');
INSERT INTO Publishers (name) VALUES ('Libertas Academica');
INSERT INTO Publishers (name) VALUES ('Eel Pie Publishing');
INSERT INTO Publishers (name) VALUES ('Hachette Book Group USA');
INSERT INTO Publishers (name) VALUES ('Northwestern University Press');
INSERT INTO Publishers (name) VALUES ('Aunt Lute Books ');
INSERT INTO Publishers (name) VALUES ('Pimlico Books at Random House');
INSERT INTO Publishers (name) VALUES ('Columbia University Press');
INSERT INTO Publishers (name) VALUES ('The Miegunyah Press');
INSERT INTO Publishers (name) VALUES ('Arcade Publishing');
INSERT INTO Publishers (name) VALUES ('Penn State University Press');
INSERT INTO Publishers (name) VALUES ('SUNY Press');
INSERT INTO Publishers (name) VALUES ('Heinemann ');
INSERT INTO Publishers (name) VALUES ('Salt Publishing');
INSERT INTO Publishers (name) VALUES ('Stein and Day ');
INSERT INTO Publishers (name) VALUES ('Progress Publishers');
INSERT INTO Publishers (name) VALUES ('Schocken Books');
INSERT INTO Publishers (name) VALUES ('Borgo Press ');
INSERT INTO Publishers (name) VALUES ('Goops Unlimited');
INSERT INTO Publishers (name) VALUES ('Grafton');
INSERT INTO Publishers (name) VALUES ('Triangle Books ');
INSERT INTO Publishers (name) VALUES ('Kogan Page ');
INSERT INTO Publishers (name) VALUES ('Miles Kelly Publishing');
INSERT INTO Publishers (name) VALUES ('Blue Ribbon Books, Garden City, New York');
INSERT INTO Publishers (name) VALUES ('Ten Speed Press');
INSERT INTO Publishers (name) VALUES ('Pecan Grove Press');
INSERT INTO Publishers (name) VALUES ('G. P. Putnam''s Sons');
INSERT INTO Publishers (name) VALUES ('Sylvan Dell Publishing');
INSERT INTO Publishers (name) VALUES ('Canongate Books');
INSERT INTO Publishers (name) VALUES ('Farrar, Straus & Giroux ');
INSERT INTO Publishers (name) VALUES ('Kessinger Publishing');


-- Populates Purchases Table
INSERT INTO Purchases (customerId, purchDate) VALUES ( 37, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 6, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 37, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 3, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 35, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 12, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 1, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 24, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 22, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 48, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 26, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 21, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 40, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 12, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 36, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 25, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 27, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 10, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 20, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 45, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 8, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 36, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 41, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 46, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 51, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 5, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 30, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 38, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 38, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 24, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 19, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 20, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 43, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 8, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 33, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 47, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 6, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 26, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 5, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 24, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 30, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 43, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 28, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 33, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 32, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 51, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 37, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 2, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 41, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 40, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 14, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 21, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 22, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 11, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 48, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 48, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 41, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 18, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 49, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 21, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 29, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 6, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 5, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 39, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 32, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 30, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 33, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 31, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 20, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 41, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 32, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 4, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 37, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 34, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 24, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 15, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 31, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 30, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 35, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 49, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 16, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 37, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 19, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 28, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 27, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 17, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 1, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 25, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 34, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 47, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 16, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 39, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 8, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 23, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 45, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 12, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 17, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 20, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 12, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 2, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 30, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 43, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 8, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 47, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 6, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 36, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 12, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 46, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 44, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 27, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 15, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 42, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 11, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 10, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 40, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 1, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 40, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 43, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 7, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 1, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 51, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 12, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 25, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 30, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 44, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 28, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 1, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 49, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 44, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 40, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 28, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 28, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 4, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 39, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 50, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 38, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 14, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 22, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 39, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 50, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 23, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 2, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 51, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 22, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 23, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 8, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 44, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 47, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 11, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 50, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 24, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 34, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 31, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 4, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 33, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 4, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 11, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 25, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 1, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 47, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 19, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 36, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 14, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 25, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 25, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 46, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 27, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 16, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 10, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 36, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 6, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 23, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 3, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 13, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 7, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 28, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 49, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 26, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 43, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 34, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 41, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 15, '2016-07-30 16:32:13');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 24, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 17, '2016-07-30 16:32:12');
INSERT INTO Purchases (customerId, purchDate) VALUES ( 9, '2016-07-30 16:32:13');


-- Populates Authors
INSERT INTO Authors (fname, lname) VALUE ('James','Joyce');
INSERT INTO Authors (fname, lname) VALUE ('F.Fitzgerald');
INSERT INTO Authors (fname, lname) VALUE ('James','Joyce');
INSERT INTO Authors (fname, lname) VALUE ('Vladimir','Nabokov');
INSERT INTO Authors (fname, lname) VALUE ('Aldous','Huxley');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Heller');
INSERT INTO Authors (fname, lname) VALUE ('Arthur','Koestler');
INSERT INTO Authors (fname, lname) VALUE ('D.H.','Lawrence');
INSERT INTO Authors (fname, lname) VALUE ('John','Steinbeck');
INSERT INTO Authors (fname, lname) VALUE ('Malcolm','Lowry');
INSERT INTO Authors (fname, lname) VALUE ('Samuel','Butler');
INSERT INTO Authors (fname, lname) VALUE ('George','Orwell');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Graves');
INSERT INTO Authors (fname, lname) VALUE ('Virginia','Woolf');
INSERT INTO Authors (fname, lname) VALUE ('Theodore','Dreiser');
INSERT INTO Authors (fname, lname) VALUE ('Carson','McCullers');
INSERT INTO Authors (fname, lname) VALUE ('Kurt','Vonnegut');
INSERT INTO Authors (fname, lname) VALUE ('Ralph','Ellison');
INSERT INTO Authors (fname, lname) VALUE ('Richard','Wright');
INSERT INTO Authors (fname, lname) VALUE ('Saul','Bellow');
INSERT INTO Authors (fname, lname) VALUE ('John','O’Hara');
INSERT INTO Authors (fname, lname) VALUE ('JohnPassos');
INSERT INTO Authors (fname, lname) VALUE ('Sherwood','Anderson');
INSERT INTO Authors (fname, lname) VALUE ('E.M.','Forster');
INSERT INTO Authors (fname, lname) VALUE ('Henry','James');
INSERT INTO Authors (fname, lname) VALUE ('Henry','James');
INSERT INTO Authors (fname, lname) VALUE ('F.Fitzgerald');
INSERT INTO Authors (fname, lname) VALUE ('JamesFarrell');
INSERT INTO Authors (fname, lname) VALUE ('FordFord');
INSERT INTO Authors (fname, lname) VALUE ('George','Orwell');
INSERT INTO Authors (fname, lname) VALUE ('Henry','James');
INSERT INTO Authors (fname, lname) VALUE ('Theodore','Dreiser');
INSERT INTO Authors (fname, lname) VALUE ('Evelyn','Waugh');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('RobertWarren');
INSERT INTO Authors (fname, lname) VALUE ('Thornton','Wilder');
INSERT INTO Authors (fname, lname) VALUE ('E.M.','Forster');
INSERT INTO Authors (fname, lname) VALUE ('James','Baldwin');
INSERT INTO Authors (fname, lname) VALUE ('Graham','Greene');
INSERT INTO Authors (fname, lname) VALUE ('William','Golding');
INSERT INTO Authors (fname, lname) VALUE ('James','Dickey');
INSERT INTO Authors (fname, lname) VALUE ('Anthony','Powell');
INSERT INTO Authors (fname, lname) VALUE ('Aldous','Huxley');
INSERT INTO Authors (fname, lname) VALUE ('Ernest','Hemingway');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Conrad');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Conrad');
INSERT INTO Authors (fname, lname) VALUE ('D.H.','Lawrence');
INSERT INTO Authors (fname, lname) VALUE ('D.H.','Lawrence');
INSERT INTO Authors (fname, lname) VALUE ('Henry','Miller');
INSERT INTO Authors (fname, lname) VALUE ('Norman','Mailer');
INSERT INTO Authors (fname, lname) VALUE ('Philip','Roth');
INSERT INTO Authors (fname, lname) VALUE ('Vladimir','Nabokov');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('Jack','Kerouac');
INSERT INTO Authors (fname, lname) VALUE ('Dashiell','Hammett');
INSERT INTO Authors (fname, lname) VALUE ('FordFord');
INSERT INTO Authors (fname, lname) VALUE ('Edith','Wharton');
INSERT INTO Authors (fname, lname) VALUE ('Max','Beerbohm');
INSERT INTO Authors (fname, lname) VALUE ('Walker','Percy');
INSERT INTO Authors (fname, lname) VALUE ('Willa','Cather');
INSERT INTO Authors (fname, lname) VALUE ('James','Jones');
INSERT INTO Authors (fname, lname) VALUE ('John','Cheever');
INSERT INTO Authors (fname, lname) VALUE ('J.D.','Salinger');
INSERT INTO Authors (fname, lname) VALUE ('Anthony','Burgess');
INSERT INTO Authors (fname, lname) VALUE ('W.Maugham');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Conrad');
INSERT INTO Authors (fname, lname) VALUE ('Sinclair','Lewis');
INSERT INTO Authors (fname, lname) VALUE ('Edith','Wharton');
INSERT INTO Authors (fname, lname) VALUE ('Lawrence','Durell');
INSERT INTO Authors (fname, lname) VALUE ('Richard','Hughes');
INSERT INTO Authors (fname, lname) VALUE ('V.S.','Naipaul');
INSERT INTO Authors (fname, lname) VALUE ('Nathanael','West');
INSERT INTO Authors (fname, lname) VALUE ('Ernest','Hemingway');
INSERT INTO Authors (fname, lname) VALUE ('Evelyn','Waugh');
INSERT INTO Authors (fname, lname) VALUE ('Muriel','Spark');
INSERT INTO Authors (fname, lname) VALUE ('James','Joyce');
INSERT INTO Authors (fname, lname) VALUE ('Rudyard','Kipling');
INSERT INTO Authors (fname, lname) VALUE ('E.M.','Forster');
INSERT INTO Authors (fname, lname) VALUE ('Evelyn','Waugh');
INSERT INTO Authors (fname, lname) VALUE ('Saul','Bellow');
INSERT INTO Authors (fname, lname) VALUE ('Wallace','Stegner');
INSERT INTO Authors (fname, lname) VALUE ('V.S.','Naipaul');
INSERT INTO Authors (fname, lname) VALUE ('Elizabeth','Bowen');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Conrad');
INSERT INTO Authors (fname, lname) VALUE ('E.L.','Doctorow');
INSERT INTO Authors (fname, lname) VALUE ('Arnold','Bennett');
INSERT INTO Authors (fname, lname) VALUE ('Jack','London');
INSERT INTO Authors (fname, lname) VALUE ('Henry','Green');
INSERT INTO Authors (fname, lname) VALUE ('Salman','Rushdie');
INSERT INTO Authors (fname, lname) VALUE ('Erskine','Caldwell');
INSERT INTO Authors (fname, lname) VALUE ('William','Kennedy');
INSERT INTO Authors (fname, lname) VALUE ('John','Fowles');
INSERT INTO Authors (fname, lname) VALUE ('Jean','Rhys');
INSERT INTO Authors (fname, lname) VALUE ('Iris','Murdoch');
INSERT INTO Authors (fname, lname) VALUE ('William','Styron');
INSERT INTO Authors (fname, lname) VALUE ('Paul','Bowles');
INSERT INTO Authors (fname, lname) VALUE ('JamesCain');
INSERT INTO Authors (fname, lname) VALUE ('J.P.','Donleavy');
INSERT INTO Authors (fname, lname) VALUE ('Booth','Tarkington');
INSERT INTO Authors (fname, lname) VALUE ('Ayn','Rand');
INSERT INTO Authors (fname, lname) VALUE ('Ayn','Rand');
INSERT INTO Authors (fname, lname) VALUE ('L.Hubbard');
INSERT INTO Authors (fname, lname) VALUE ('J.R.R.','Tolkien');
INSERT INTO Authors (fname, lname) VALUE ('Harper','Lee');
INSERT INTO Authors (fname, lname) VALUE ('George','Orwell');
INSERT INTO Authors (fname, lname) VALUE ('Ayn','Rand');
INSERT INTO Authors (fname, lname) VALUE ('Ayn','Rand');
INSERT INTO Authors (fname, lname) VALUE ('L.Hubbard');
INSERT INTO Authors (fname, lname) VALUE ('L.Hubbard');
INSERT INTO Authors (fname, lname) VALUE ('James','Joyce');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Heller');
INSERT INTO Authors (fname, lname) VALUE ('F.Fitzgerald');
INSERT INTO Authors (fname, lname) VALUE ('Frank','Herbert');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Nevil','Shute');
INSERT INTO Authors (fname, lname) VALUE ('Aldous','Huxley');
INSERT INTO Authors (fname, lname) VALUE ('J.D.','Salinger');
INSERT INTO Authors (fname, lname) VALUE ('George','Orwell');
INSERT INTO Authors (fname, lname) VALUE ('Thomas','Pynchon');
INSERT INTO Authors (fname, lname) VALUE ('John','Steinbeck');
INSERT INTO Authors (fname, lname) VALUE ('Kurt','Vonnegut');
INSERT INTO Authors (fname, lname) VALUE ('Margaret','Mitchell');
INSERT INTO Authors (fname, lname) VALUE ('William','Golding');
INSERT INTO Authors (fname, lname) VALUE ('Jack','Schaefer');
INSERT INTO Authors (fname, lname) VALUE ('Nevil','Shute');
INSERT INTO Authors (fname, lname) VALUE ('John','Irving');
INSERT INTO Authors (fname, lname) VALUE ('Stephen','King');
INSERT INTO Authors (fname, lname) VALUE ('John','Fowles');
INSERT INTO Authors (fname, lname) VALUE ('Toni','Morrison');
INSERT INTO Authors (fname, lname) VALUE ('E.R.','Eddison');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('Vladimir','Nabokov');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('W.Maugham');
INSERT INTO Authors (fname, lname) VALUE ('Flannery','O’Connor');
INSERT INTO Authors (fname, lname) VALUE ('Malcolm','Lowry');
INSERT INTO Authors (fname, lname) VALUE ('Robertson','Davies');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('Jack','Kerouac');
INSERT INTO Authors (fname, lname) VALUE ('Joseph','Conrad');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('H.P.','Lovecraft');
INSERT INTO Authors (fname, lname) VALUE ('Mickey','Spillane');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('Virginia','Woolf');
INSERT INTO Authors (fname, lname) VALUE ('Walker','Percy');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('Douglas','Adams');
INSERT INTO Authors (fname, lname) VALUE ('Carson','McCullers');
INSERT INTO Authors (fname, lname) VALUE ('Margaret','Atwood');
INSERT INTO Authors (fname, lname) VALUE ('Cormac','McCarthy');
INSERT INTO Authors (fname, lname) VALUE ('Anthony','Burgess');
INSERT INTO Authors (fname, lname) VALUE ('Nevil','Shute');
INSERT INTO Authors (fname, lname) VALUE ('James','Joyce');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('OrsonCard');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('William','Gaddis');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Ernest','Hemingway');
INSERT INTO Authors (fname, lname) VALUE ('John','Irving');
INSERT INTO Authors (fname, lname) VALUE ('Ray','Bradbury');
INSERT INTO Authors (fname, lname) VALUE ('Shirley','Jackson');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('Henry','Miller');
INSERT INTO Authors (fname, lname) VALUE ('Ralph','Ellison');
INSERT INTO Authors (fname, lname) VALUE ('Terri','Windling');
INSERT INTO Authors (fname, lname) VALUE ('John','Fowles');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Pirsig');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Graves');
INSERT INTO Authors (fname, lname) VALUE ('Jack','London');
INSERT INTO Authors (fname, lname) VALUE ('Flann','O’Brien');
INSERT INTO Authors (fname, lname) VALUE ('Ray','Bradbury');
INSERT INTO Authors (fname, lname) VALUE ('Sinclair','Lewis');
INSERT INTO Authors (fname, lname) VALUE ('Richard','Adams');
INSERT INTO Authors (fname, lname) VALUE ('WilliamBurroughs');
INSERT INTO Authors (fname, lname) VALUE ('Tom','Clancy');
INSERT INTO Authors (fname, lname) VALUE ('LaurellHamilton');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Stephen','King');
INSERT INTO Authors (fname, lname) VALUE ('Thomas','Pynchon');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Heinlein');
INSERT INTO Authors (fname, lname) VALUE ('Evelyn','Waugh');
INSERT INTO Authors (fname, lname) VALUE ('William','Faulkner');
INSERT INTO Authors (fname, lname) VALUE ('Ken','Kesey');
INSERT INTO Authors (fname, lname) VALUE ('Ernest','Hemingway');
INSERT INTO Authors (fname, lname) VALUE ('Paul','Bowles');
INSERT INTO Authors (fname, lname) VALUE ('Ken','Kesey');
INSERT INTO Authors (fname, lname) VALUE ('Willa','Cather');
INSERT INTO Authors (fname, lname) VALUE ('CharlesLint');
INSERT INTO Authors (fname, lname) VALUE ('Cormac','McCarthy');
INSERT INTO Authors (fname, lname) VALUE ('Robert','Holdstock');
INSERT INTO Authors (fname, lname) VALUE ('Richard','Bach');
INSERT INTO Authors (fname, lname) VALUE ('Robertson','Davies');
INSERT INTO Authors (fname, lname) VALUE ('Salman','Rushdie');

-- Populates Book Table
INSERT INTO Books (title, publisherId) VALUES ('ULYSSES',  1);
INSERT INTO Books (title, publisherId) VALUES ('THE GREAT GATSBY',  2);
INSERT INTO Books (title, publisherId) VALUES ('A PORTRAIT OF THE ARTIST AS A YOUNG MAN',  3);
INSERT INTO Books (title, publisherId) VALUES ('LOLITA',  4);
INSERT INTO Books (title, publisherId) VALUES ('BRAVE NEW WORLD',  5);
INSERT INTO Books (title, publisherId) VALUES ('THE SOUND AND THE FURY',  6);
INSERT INTO Books (title, publisherId) VALUES ('CATCH-22',  7);
INSERT INTO Books (title, publisherId) VALUES ('DARKNESS AT NOON',  8);
INSERT INTO Books (title, publisherId) VALUES ('SONS AND LOVERS',  9);
INSERT INTO Books (title, publisherId) VALUES ('THE GRAPES OF WRATH',  10);
INSERT INTO Books (title, publisherId) VALUES ('UNDER THE VOLCANO',  11);
INSERT INTO Books (title, publisherId) VALUES ('THE WAY OF ALL FLESH',  12);
INSERT INTO Books (title, publisherId) VALUES ('1984',  13);
INSERT INTO Books (title, publisherId) VALUES ('I, CLAUDIUS',  14);
INSERT INTO Books (title, publisherId) VALUES ('TO THE LIGHTHOUSE',  15);
INSERT INTO Books (title, publisherId) VALUES ('AN AMERICAN TRAGEDY',  16);
INSERT INTO Books (title, publisherId) VALUES ('THE HEART IS A LONELY HUNTER',  17);
INSERT INTO Books (title, publisherId) VALUES ('SLAUGHTERHOUSE-FIVE',  18);
INSERT INTO Books (title, publisherId) VALUES ('INVISIBLE MAN',  19);
INSERT INTO Books (title, publisherId) VALUES ('NATIVE SON',  20);
INSERT INTO Books (title, publisherId) VALUES ('HENDERSON THE RAIN KING',  21);
INSERT INTO Books (title, publisherId) VALUES ('APPOINTMENT IN SAMARRA',  22);
INSERT INTO Books (title, publisherId) VALUES ('U.S.A.(trilogy)',  23);
INSERT INTO Books (title, publisherId) VALUES ('WINESBURG, OHIO',  24);
INSERT INTO Books (title, publisherId) VALUES ('A PASSAGE TO INDIA',  25);
INSERT INTO Books (title, publisherId) VALUES ('THE WINGS OF THE DOVE',  26);
INSERT INTO Books (title, publisherId) VALUES ('THE AMBASSADORS',  27);
INSERT INTO Books (title, publisherId) VALUES ('TENDER IS THE NIGHT',  28);
INSERT INTO Books (title, publisherId) VALUES ('THE STUDS LONIGAN TRILOGY',  29);
INSERT INTO Books (title, publisherId) VALUES ('THE GOOD SOLDIER',  30);
INSERT INTO Books (title, publisherId) VALUES ('ANIMAL FARM',  31);
INSERT INTO Books (title, publisherId) VALUES ('THE GOLDEN BOWL',  32);
INSERT INTO Books (title, publisherId) VALUES ('SISTER CARRIE',  33);
INSERT INTO Books (title, publisherId) VALUES ('A HANDFUL OF DUST',  34);
INSERT INTO Books (title, publisherId) VALUES ('AS I LAY DYING',  35);
INSERT INTO Books (title, publisherId) VALUES ('ALL THE KING’S MEN',  36);
INSERT INTO Books (title, publisherId) VALUES ('THE BRIDGE OF SAN LUIS REY',  37);
INSERT INTO Books (title, publisherId) VALUES ('HOWARDS END',  38);
INSERT INTO Books (title, publisherId) VALUES ('GO TELL IT ON THE MOUNTAIN',  39);
INSERT INTO Books (title, publisherId) VALUES ('THE HEART OF THE MATTER',  40);
INSERT INTO Books (title, publisherId) VALUES ('LORD OF THE FLIES',  41);
INSERT INTO Books (title, publisherId) VALUES ('DELIVERANCE',  42);
INSERT INTO Books (title, publisherId) VALUES ('A DANCE TO THE MUSIC OF TIME (series)',  43);
INSERT INTO Books (title, publisherId) VALUES ('POINT COUNTER POINT',  44);
INSERT INTO Books (title, publisherId) VALUES ('THE SUN ALSO RISES',  45);
INSERT INTO Books (title, publisherId) VALUES ('THE SECRET AGENT',  46);
INSERT INTO Books (title, publisherId) VALUES ('NOSTROMO',  47);
INSERT INTO Books (title, publisherId) VALUES ('THE RAINBOW',  48);
INSERT INTO Books (title, publisherId) VALUES ('WOMEN IN LOVE',  49);
INSERT INTO Books (title, publisherId) VALUES ('TROPIC OF CANCER',  50);
INSERT INTO Books (title, publisherId) VALUES ('THE NAKED AND THE DEAD',  51);
INSERT INTO Books (title, publisherId) VALUES ('PORTNOY’S COMPLAINT',  52);
INSERT INTO Books (title, publisherId) VALUES ('PALE FIRE',  53);
INSERT INTO Books (title, publisherId) VALUES ('LIGHT IN AUGUST',  54);
INSERT INTO Books (title, publisherId) VALUES ('ON THE ROAD',  55);
INSERT INTO Books (title, publisherId) VALUES ('THE MALTESE FALCON',  56);
INSERT INTO Books (title, publisherId) VALUES ('PARADE’S END',  57);
INSERT INTO Books (title, publisherId) VALUES ('THE AGE OF INNOCENCE',  58);
INSERT INTO Books (title, publisherId) VALUES ('ZULEIKA DOBSON',  59);
INSERT INTO Books (title, publisherId) VALUES ('THE MOVIEGOER',  60);
INSERT INTO Books (title, publisherId) VALUES ('DEATH COMES FOR THE ARCHBISHOP',  61);
INSERT INTO Books (title, publisherId) VALUES ('FROM HERE TO ETERNITY',  62);
INSERT INTO Books (title, publisherId) VALUES ('THE WAPSHOT CHRONICLES',  63);
INSERT INTO Books (title, publisherId) VALUES ('THE CATCHER IN THE RYE',  64);
INSERT INTO Books (title, publisherId) VALUES ('A CLOCKWORK ORANGE',  65);
INSERT INTO Books (title, publisherId) VALUES ('OF HUMAN BONDAGE',  66);
INSERT INTO Books (title, publisherId) VALUES ('HEART OF DARKNESS',  67);
INSERT INTO Books (title, publisherId) VALUES ('MAIN STREET',  68);
INSERT INTO Books (title, publisherId) VALUES ('THE HOUSE OF MIRTH',  69);
INSERT INTO Books (title, publisherId) VALUES ('THE ALEXANDRIA QUARTET',  70);
INSERT INTO Books (title, publisherId) VALUES ('A HIGH WIND IN JAMAICA',  71);
INSERT INTO Books (title, publisherId) VALUES ('A HOUSE FOR MR BISWAS',  72);
INSERT INTO Books (title, publisherId) VALUES ('THE DAY OF THE LOCUST',  73);
INSERT INTO Books (title, publisherId) VALUES ('A FAREWELL TO ARMS',  74);
INSERT INTO Books (title, publisherId) VALUES ('SCOOP',  75);
INSERT INTO Books (title, publisherId) VALUES ('THE PRIME OF MISS JEAN BRODIE',  76);
INSERT INTO Books (title, publisherId) VALUES ('FINNEGANS WAKE',  77);
INSERT INTO Books (title, publisherId) VALUES ('KIM',  78);
INSERT INTO Books (title, publisherId) VALUES ('A ROOM WITH A VIEW',  79);
INSERT INTO Books (title, publisherId) VALUES ('BRIDESHEAD REVISITED',  80);
INSERT INTO Books (title, publisherId) VALUES ('THE ADVENTURES OF AUGIE MARCH',  81);
INSERT INTO Books (title, publisherId) VALUES ('ANGLE OF REPOSE',  82);
INSERT INTO Books (title, publisherId) VALUES ('A BEND IN THE RIVER',  83);
INSERT INTO Books (title, publisherId) VALUES ('THE DEATH OF THE HEART',  84);
INSERT INTO Books (title, publisherId) VALUES ('LORD JIM',  85);
INSERT INTO Books (title, publisherId) VALUES ('RAGTIME',  86);
INSERT INTO Books (title, publisherId) VALUES ('THE OLD WIVES’ TALE',  87);
INSERT INTO Books (title, publisherId) VALUES ('THE CALL OF THE WILD',  88);
INSERT INTO Books (title, publisherId) VALUES ('LOVING',  89);
INSERT INTO Books (title, publisherId) VALUES ('MIDNIGHT’S CHILDREN',  90);
INSERT INTO Books (title, publisherId) VALUES ('TOBACCO ROAD',  91);
INSERT INTO Books (title, publisherId) VALUES ('IRONWEED',  92);
INSERT INTO Books (title, publisherId) VALUES ('THE MAGUS',  93);
INSERT INTO Books (title, publisherId) VALUES ('WIDE SARGASSO SEA',  94);
INSERT INTO Books (title, publisherId) VALUES ('UNDER THE NET',  95);
INSERT INTO Books (title, publisherId) VALUES ('SOPHIE’S CHOICE',  96);
INSERT INTO Books (title, publisherId) VALUES ('THE SHELTERING SKY',  97);
INSERT INTO Books (title, publisherId) VALUES ('THE POSTMAN ALWAYS RINGS TWICE',  98);
INSERT INTO Books (title, publisherId) VALUES ('THE GINGER MAN',  99);
INSERT INTO Books (title, publisherId) VALUES ('THE MAGNIFICENT AMBERSONS',  100);
INSERT INTO Books (title, publisherId) VALUES ('ATLAS SHRUGGED',  101);
INSERT INTO Books (title, publisherId) VALUES ('THE FOUNTAINHEAD',  102);
INSERT INTO Books (title, publisherId) VALUES ('BATTLEFIELD EARTH',  103);
INSERT INTO Books (title, publisherId) VALUES ('THE LORD OF THE RINGS',  104);
INSERT INTO Books (title, publisherId) VALUES ('TO KILL A MOCKINGBIRD',  105);
INSERT INTO Books (title, publisherId) VALUES ('1984',  106);
INSERT INTO Books (title, publisherId) VALUES ('ANTHEM',  107);
INSERT INTO Books (title, publisherId) VALUES ('WE THE LIVING',  108);
INSERT INTO Books (title, publisherId) VALUES ('MISSION EARTH',  109);
INSERT INTO Books (title, publisherId) VALUES ('FEAR',  110);
INSERT INTO Books (title, publisherId) VALUES ('ULYSSES',  111);
INSERT INTO Books (title, publisherId) VALUES ('CATCH-22',  112);
INSERT INTO Books (title, publisherId) VALUES ('THE GREAT GATSBY',  113);
INSERT INTO Books (title, publisherId) VALUES ('DUNE',  114);
INSERT INTO Books (title, publisherId) VALUES ('THE MOON IS A HARSH MISTRESS',  115);
INSERT INTO Books (title, publisherId) VALUES ('STRANGER IN A STRANGE LAND',  116);
INSERT INTO Books (title, publisherId) VALUES ('A TOWN LIKE ALICE',  117);
INSERT INTO Books (title, publisherId) VALUES ('BRAVE NEW WORLD',  118);
INSERT INTO Books (title, publisherId) VALUES ('THE CATCHER IN THE RYE',  119);
INSERT INTO Books (title, publisherId) VALUES ('ANIMAL FARM',  120);
INSERT INTO Books (title, publisherId) VALUES ('GRAVITY’S RAINBOW',  121);
INSERT INTO Books (title, publisherId) VALUES ('THE GRAPES OF WRATH',  122);
INSERT INTO Books (title, publisherId) VALUES ('SLAUGHTERHOUSE FIVE',  123);
INSERT INTO Books (title, publisherId) VALUES ('GONE WITH THE WIND',  124);
INSERT INTO Books (title, publisherId) VALUES ('LORD OF THE FLIES',  125);
INSERT INTO Books (title, publisherId) VALUES ('SHANE',  126);
INSERT INTO Books (title, publisherId) VALUES ('TRUSTEE FROM THE TOOLROOM',  127);
INSERT INTO Books (title, publisherId) VALUES ('A PRAYER FOR OWEN MEANY',  128);
INSERT INTO Books (title, publisherId) VALUES ('THE STAND',  129);
INSERT INTO Books (title, publisherId) VALUES ('THE FRENCH LIEUTENANT’S WOMAN',  130);
INSERT INTO Books (title, publisherId) VALUES ('BELOVED',  131);
INSERT INTO Books (title, publisherId) VALUES ('THE WORM OUROBOROS',  132);
INSERT INTO Books (title, publisherId) VALUES ('THE SOUND AND THE FURY',  133);
INSERT INTO Books (title, publisherId) VALUES ('LOLITA',  134);
INSERT INTO Books (title, publisherId) VALUES ('MOONHEART',  135);
INSERT INTO Books (title, publisherId) VALUES ('ABSALOM, ABSALOM!',  136);
INSERT INTO Books (title, publisherId) VALUES ('OF HUMAN BONDAGE',  137);
INSERT INTO Books (title, publisherId) VALUES ('WISE BLOOD',  138);
INSERT INTO Books (title, publisherId) VALUES ('UNDER THE VOLCANO',  139);
INSERT INTO Books (title, publisherId) VALUES ('FIFTH BUSINESS',  140);
INSERT INTO Books (title, publisherId) VALUES ('SOMEPLACE TO BE FLYING',  141);
INSERT INTO Books (title, publisherId) VALUES ('ON THE ROAD',  142);
INSERT INTO Books (title, publisherId) VALUES ('HEART OF DARKNESS',  143);
INSERT INTO Books (title, publisherId) VALUES ('YARROW',  144);
INSERT INTO Books (title, publisherId) VALUES ('AT THE MOUNTAINS OF MADNESS',  145);
INSERT INTO Books (title, publisherId) VALUES ('ONE LONELY NIGHT',  146);
INSERT INTO Books (title, publisherId) VALUES ('MEMORY AND DREAM',  147);
INSERT INTO Books (title, publisherId) VALUES ('TO THE LIGHTHOUSE',  148);
INSERT INTO Books (title, publisherId) VALUES ('THE MOVIEGOER',  149);
INSERT INTO Books (title, publisherId) VALUES ('TRADER',  150);
INSERT INTO Books (title, publisherId) VALUES ('THE HITCHHIKER’S GUIDE TO THE GALAXY',  151);
INSERT INTO Books (title, publisherId) VALUES ('THE HEART IS A LONELY HUNTER',  152);
INSERT INTO Books (title, publisherId) VALUES ('THE HANDMAID’S TALE',  153);
INSERT INTO Books (title, publisherId) VALUES ('BLOOD MERIDIAN',  154);
INSERT INTO Books (title, publisherId) VALUES ('A CLOCKWORK ORANGE',  155);
INSERT INTO Books (title, publisherId) VALUES ('ON THE BEACH',  156);
INSERT INTO Books (title, publisherId) VALUES ('A PORTRAIT OF THE ARTIST AS A YOUNG MAN',  157);
INSERT INTO Books (title, publisherId) VALUES ('GREENMANTLE',  158);
INSERT INTO Books (title, publisherId) VALUES ('ENDER’S GAME',  159);
INSERT INTO Books (title, publisherId) VALUES ('THE LITTLE COUNTRY',  160);
INSERT INTO Books (title, publisherId) VALUES ('THE RECOGNITIONS',  161);
INSERT INTO Books (title, publisherId) VALUES ('STARSHIP TROOPERS',  162);
INSERT INTO Books (title, publisherId) VALUES ('THE SUN ALSO RISES',  163);
INSERT INTO Books (title, publisherId) VALUES ('THE WORLD ACCORDING TO GARP',  164);
INSERT INTO Books (title, publisherId) VALUES ('SOMETHING WICKED THIS WAY COMES',  165);
INSERT INTO Books (title, publisherId) VALUES ('THE HAUNTING OF HILL HOUSE',  166);
INSERT INTO Books (title, publisherId) VALUES ('AS I LAY DYING',  167);
INSERT INTO Books (title, publisherId) VALUES ('TROPIC OF CANCER',  168);
INSERT INTO Books (title, publisherId) VALUES ('INVISIBLE MAN',  169);
INSERT INTO Books (title, publisherId) VALUES ('THE WOOD WIFE',  170);
INSERT INTO Books (title, publisherId) VALUES ('THE MAGUS',  171);
INSERT INTO Books (title, publisherId) VALUES ('THE DOOR INTO SUMMER',  172);
INSERT INTO Books (title, publisherId) VALUES ('ZEN AND THE ART OF MOTORCYCLE MAINTENANCE',  173);
INSERT INTO Books (title, publisherId) VALUES ('I, CLAUDIUS',  174);
INSERT INTO Books (title, publisherId) VALUES ('THE CALL OF THE WILD',  175);
INSERT INTO Books (title, publisherId) VALUES ('AT SWIM-TWO-BIRDS',  176);
INSERT INTO Books (title, publisherId) VALUES ('FARENHEIT 451',  177);
INSERT INTO Books (title, publisherId) VALUES ('ARROWSMITH',  178);
INSERT INTO Books (title, publisherId) VALUES ('WATERSHIP DOWN',  179);
INSERT INTO Books (title, publisherId) VALUES ('NAKED LUNCH',  180);
INSERT INTO Books (title, publisherId) VALUES ('THE HUNT FOR RED OCTOBER',  181);
INSERT INTO Books (title, publisherId) VALUES ('GUILTY PLEASURES',  182);
INSERT INTO Books (title, publisherId) VALUES ('THE PUPPET MASTERS',  183);
INSERT INTO Books (title, publisherId) VALUES ('IT',  184);
INSERT INTO Books (title, publisherId) VALUES ('V.',  185);
INSERT INTO Books (title, publisherId) VALUES ('DOUBLE STAR',  186);
INSERT INTO Books (title, publisherId) VALUES ('CITIZEN OF THE GALAXY',  187);
INSERT INTO Books (title, publisherId) VALUES ('BRIDESHEAD REVISITED',  188);
INSERT INTO Books (title, publisherId) VALUES ('LIGHT IN AUGUST',  189);
INSERT INTO Books (title, publisherId) VALUES ('ONE FLEW OVER THE CUCKOO’S NEST',  190);
INSERT INTO Books (title, publisherId) VALUES ('A FAREWELL TO ARMS',  191);
INSERT INTO Books (title, publisherId) VALUES ('THE SHELTERING SKY',  192);
INSERT INTO Books (title, publisherId) VALUES ('SOMETIMES A GREAT NOTION',  193);
INSERT INTO Books (title, publisherId) VALUES ('MY ANTONIA',  194);
INSERT INTO Books (title, publisherId) VALUES ('MULENGRO',  195);
INSERT INTO Books (title, publisherId) VALUES ('SUTTREE',  196);
INSERT INTO Books (title, publisherId) VALUES ('MYTHAGO WOOD',  197);
INSERT INTO Books (title, publisherId) VALUES ('ILLUSIONS',  198);
INSERT INTO Books (title, publisherId) VALUES ('THE CUNNING MAN',  199);

-- Populates 